application: feed2me17
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/
  static_dir: static

- url: /check_feeds
  script: main.app
  login: admin

- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
